[input]
    [input.accesslog]
        type = "file"
        path = "/Users/gao/test111"
        format = "text"
#        regex = "(\\w+) (\\S+) \\w+ (\\w+)"
        regex = "(?P<level>\\w+) (?P<time>\\S+) \\w+ (?P<name>\\w+)"


[handler]
    [handler.accesslog]
         script_path = "/Users/gao/code/gowork/src/logDog/myHandler.lua"      # lua 脚本路径
        [handler.accesslog.add_data]
            school_id = "123"
            class_id = "123"

[output]
    [output.other]
        type = "stdout"
    [output.accesslog2]
        type = "http"
        http_url = "http://localhost:9000"
        [output.accesslog2.headers]
            Auth = "123456"
    [output.accesslog]
        type = "redis"
        redis_addr = "localhost:6379"
        redis_db = 0
        redis_key = "logdog"
